//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheapees
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonFulfilledInventory
    {
        public string FbaSku { get; set; }
        public string Asin { get; set; }
        public string Fnsku { get; set; }
        public Nullable<int> FulfillableQuantity { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> InboundWorkingQuantity { get; set; }
        public Nullable<int> InboundShippedQuantity { get; set; }
        public Nullable<int> InboundReceivingQuantity { get; set; }
    }
}
