//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheapees
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonPrepInstruction
    {
        public string Asin { get; set; }
        public string Labelling { get; set; }
        public string PrepRequired { get; set; }
    }
}
