//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheapees
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantFulfilledSale
    {
        public string Invoice { get; set; }
        public string Marketplace { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string Sku { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    }
}
