//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheapees
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStatus
    {
        public string ServiceId { get; set; }
        public Nullable<System.DateTime> LastSuccessfulUpdate { get; set; }
    }
}
